### ISSUE TITLE
Source code contains commented out code 

### ISSUE THREAD

**Issue by OBITORASU** [l3th4l/Word-Filter-Bot#5]
## Description:
Some of the comment out code has been pushed into the github repo. I guess it is a better idea not to push with commented code in place. Currently all the files in ```model``` folder has some commented out unecessary code, it would be good if all these lines are removed from the main repo.

## Extra 
If possible add a ```.gitignore``` and remove the ```__pycache__``` folder in ```model```. It is like a general rule of thumb to not add the ```__pycache__``` folder in the github repo.

**Comment by l3th4l** [comment]
Fixed this issue in the latest commit
